name: TastyLog CI
on:
    pull_request:
        branches: [ develop ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v4

            - name: Setup JDK 17
              uses: actions/setup-java@v4
              with:
                  distribution: 'corretto'
                  java-version: '17'

            - name: Setup Android SDK
              uses: android-actions/setup-android@v3

            - name: Grant execute permission for gradlew
              run: chmod +x gradlew

            - name: Decode google-services.json
              env:
                FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
              run: echo $FIREBASE_SECRET > app/google-services.json

            - name: Access Local Properties
              env:
                  BASE_URL: ${{ secrets.BASE_URL }}
                  NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
                  NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
                  KAKAO_SCHEME: ${{ secrets.KAKAO_SCHEME }}
                  KAKAO_SCHEME_MANIFEST: ${{ secrets.KAKAO_SCHEME }}
                  KAKAO_SHARE_KEY: ${{ secrets.KAKAO_SHARE_KEY }}
              run: |
                  echo "base.url=\"$BASE_URL\"" >> local.properties
                  echo "naver.client.id=\"$NAVER_CLIENT_ID\"" >> local.properties
                  echo "naver.client.secret=\"$NAVER_CLIENT_SECRET\"" >> local.properties
                  echo "kakao.scheme=\"$KAKAO_SCHEME\"" >> local.properties
                  echo "kakao.scheme.manifest=\"$KAKAO_SCHEME_MANIFEST\"" >> local.properties
                  echo "kakao.share.key=\"$KAKAO_SHARE_KEY\"" >> local.properties

            - name: Run ktlint
              run: ./gradlew ktlintCheck

            - name: Build Android project
              run: ./gradlew assembleDebug

            - name: Cache Gradle packages
              uses: actions/cache@v2
              with:
                path: |
                  ~/.gradle/caches
                  ~/.gradle/wrapper
                key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
                restore-keys: |
                  ${{ runner.os }}-gradle-
